<?php

/**
 * @file
 * Module file for Annotations
 */

/**
 * @defgroup annotations AustESE Annotations
 * @ingroup austese
 * @{
 * AustESE Annotations
 *
 */

/**
 * Implements hook_help().
 *
 */
function annotations_help($path, $arg) {
  switch ($path) {
    case 'annotations':
      return t('AustESE Annotations');
    case 'admin/help#annotations':
      return t('AustESE Annotations');
  }
}

/**
 * Implements hook_permission().
 *
 */
function annotations_permission() {
  return array(
    'view annotations' => array(
      'title' => t('View annotations'),
      'description' => t('Allow users to view annotations'),
    )
  );
}

/**
 * Implements hook_menu().
 *
 *
 * @see hook_menu()
 * @see menu_example
 */
function annotations_menu() {
  // view annotation tool on a separate page
  $items['annotations'] = array(
    'title' => 'Annotations',
    'page callback' => 'annotations_toc',
    'access arguments' => array('view annotations'),
    'type' => MENU_CALLBACK
  );
  $items['annotations/my-annotations'] = array(
    'title' => 'My Annotations',
    'page callback' => 'annotations_mine',
    'access arguments' => array('view annotations'),
    'type' => MENU_CALLBACK
  );
  $items['annotations/search'] = array(
    'title' => 'Search Annotations',
    'page callback' => 'annotations_search',
    'access arguments' => array('view annotations'),
    'type' => MENU_CALLBACK
  );
  return $items;
}
function annotations_toc() {
  $list[] = l("My Annotations","annotations/my-annotations");
  $list[] = l("Search Annotations","annotations/search");
  $render_array['repository_list'] = array(
    '#theme' => 'item_list',  
    '#items' => $list
  );
  return $render_array;
}
function annotations_search($resources=null) {
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Annotations','annotations');
  $breadcrumb[] = t(drupal_get_title()); 
  drupal_set_breadcrumb($breadcrumb);
  return theme('annosearch',array('resources'=>$resources));
}
function annotations_mine($resources=null) {
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l('Annotations','annotations');
  $breadcrumb[] = t(drupal_get_title()); 
  drupal_set_breadcrumb($breadcrumb);
  return theme('myannos',array('resources'=>$resources));
}
# insert annotation scripts into all pages, as long as user is logged in (for now until we implement auth support)
function annotations_page_build(&$page) {
  global $user;
  if ($user->uid) {
    $modulePath = drupal_get_path('module', 'annotations');
    drupal_add_css($modulePath . '/lib/css/imgareaselect-default.css', array('every_page' => TRUE));
    drupal_add_css($modulePath . '/lib/annotator/annotator.min.css', array('every_page' => TRUE));
    drupal_add_css($modulePath . '/annotations.css', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/scripts/jquery.timeago.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/scripts/jquery.ba-resize.min.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/scripts/jquery.waitforimages.min.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/scripts/jquery.imgareaselect.min.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.tags.min.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib//annotator/annotator.permissions.min.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.lorestore.js',array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.image.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.motivations.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/lib/annotator/annotator.prov.js', array('every_page' => TRUE));
    drupal_add_js($modulePath . '/annotations.js', array('every_page' => TRUE));
  }
  
}

function annotations_theme(){
 return array(
    'annosearch' => array(
       'template' => 'annosearch',
       'variables' => array('resources'=> null)
     ),
     'myannos' => array(
       'template' => 'annotationspage',
       'variables' => array('resources'=> null)
     )
 );
}

/**
 * @} End of "defgroup annotations".
 */
